#!/usr/bin/env python3
"""
PGDTS — Surface-Level Text Alignment Evaluation
================================================
Computes TF-IDF, ROUGE-1, ROUGE-2, and ROUGE-L scores between
model predictions and reference decisions.

Metrics:
  - TF-IDF   : Cosine similarity of TF-IDF vectors (word-level)
  - ROUGE-N  : N-gram overlap (N=1,2)
  - ROUGE-L  : Longest Common Subsequence (LCS) based F-measure
"""

import argparse
import json
import os
import re
import sys
from typing import List, Dict, Any

import numpy as np
from rouge_score import rouge_scorer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="PGDTS Surface-Level Evaluation")
    parser.add_argument("--predictions", type=str, required=True,
                        help="Path to predictions JSONL (generated by inference.py)")
    parser.add_argument("--references", type=str, required=True,
                        help="Path to ground-truth JSONL (original val/train data)")
    parser.add_argument("--output", type=str, default="./results/surface_metrics.json",
                        help="Path to write metrics JSON")
    return parser.parse_args()


def load_jsonl(path: str) -> List[Dict[str, Any]]:
    data = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            data.append(json.loads(line))
    return data


def normalize_text(text: str) -> str:
    """Lowercase, strip, and collapse whitespace."""
    text = text.lower().strip()
    text = re.sub(r"\s+", " ", text)
    return text


def compute_tfidf_similarity(predictions: List[str], references: List[str]) -> Dict[str, float]:
    """
    Compute TF-IDF cosine similarity between predicted and reference texts.
    We fit the vectorizer on all unique texts (train-like) and then compute
    pairwise cosine similarity between aligned prediction-reference pairs.
    """
    norm_preds = [normalize_text(p) for p in predictions]
    norm_refs = [normalize_text(r) for r in references]

    # Fit on the union of all texts to get a shared vocabulary
    all_texts = list(set(norm_preds + norm_refs))
    vectorizer = TfidfVectorizer(
        lowercase=True,
        token_pattern=r"(?u)\b\w+\b",  # word-level tokens
        ngram_range=(1, 1),
        norm="l2",
        smooth_idf=True,
    )
    vectorizer.fit(all_texts)

    pred_vectors = vectorizer.transform(norm_preds)
    ref_vectors = vectorizer.transform(norm_refs)

    # Pairwise cosine similarity (diagonal elements)
    similarities = cosine_similarity(pred_vectors, ref_vectors)
    pairwise_scores = np.diag(similarities)

    return {
        "tfidf_mean": float(np.mean(pairwise_scores)),
        "tfidf_std": float(np.std(pairwise_scores)),
        "tfidf_scores": pairwise_scores.tolist(),
    }


def compute_rouge(predictions: List[str], references: List[str]) -> Dict[str, Any]:
    """Compute ROUGE-1, ROUGE-2, ROUGE-L using the official rouge-score library."""
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

    rouge1_f, rouge2_f, rougeL_f = [], [], []
    for pred, ref in tqdm(zip(predictions, references), total=len(predictions), desc="ROUGE"):
        scores = scorer.score(ref, pred)
        rouge1_f.append(scores["rouge1"].fmeasure)
        rouge2_f.append(scores["rouge2"].fmeasure)
        rougeL_f.append(scores["rougeL"].fmeasure)

    return {
        "rouge1": {
            "mean": float(np.mean(rouge1_f)),
            "std": float(np.std(rouge1_f)),
            "scores": rouge1_f,
        },
        "rouge2": {
            "mean": float(np.mean(rouge2_f)),
            "std": float(np.std(rouge2_f)),
            "scores": rouge2_f,
        },
        "rougeL": {
            "mean": float(np.mean(rougeL_f)),
            "std": float(np.std(rougeL_f)),
            "scores": rougeL_f,
        },
    }


def main():
    args = parse_args()

    print(f"[INFO] Loading predictions: {args.predictions}")
    pred_data = load_jsonl(args.predictions)
    print(f"[INFO] Loading references:  {args.references}")
    ref_data = load_jsonl(args.references)

    if len(pred_data) != len(ref_data):
        print(f"[WARN] Mismatch in sample counts: preds={len(pred_data)}, refs={len(ref_data)}")
        min_len = min(len(pred_data), len(ref_data))
        pred_data = pred_data[:min_len]
        ref_data = ref_data[:min_len]

    # Extract text fields
    predictions = [item.get("prediction", "").strip() for item in pred_data]

    # For references, try "messages" first (last assistant turn), then fallback to "reference"
    references = []
    for item in ref_data:
        msgs = item.get("messages", [])
        if msgs and msgs[-1].get("role") == "assistant":
            references.append(msgs[-1]["content"].strip())
        else:
            references.append(item.get("reference", "").strip())

    # -----------------------------------------------------------------------
    # Compute metrics
    # -----------------------------------------------------------------------
    print("[INFO] Computing TF-IDF similarity ...")
    tfidf_results = compute_tfidf_similarity(predictions, references)

    print("[INFO] Computing ROUGE scores ...")
    rouge_results = compute_rouge(predictions, references)

    metrics = {
        "num_samples": len(predictions),
        "tfidf": tfidf_results["tfidf_mean"],
        "rouge1": rouge_results["rouge1"]["mean"],
        "rouge2": rouge_results["rouge2"]["mean"],
        "rougeL": rouge_results["rougeL"]["mean"],
        "details": {
            "tfidf": tfidf_results,
            "rouge": rouge_results,
        },
    }

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2, ensure_ascii=False)

    print("\n========================================")
    print("Surface-Level Evaluation Results")
    print("========================================")
    print(f"  Samples : {metrics['num_samples']}")
    print(f"  TF-IDF  : {metrics['tfidf']:.4f}")
    print(f"  ROUGE-1 : {metrics['rouge1']:.4f}")
    print(f"  ROUGE-2 : {metrics['rouge2']:.4f}")
    print(f"  ROUGE-L : {metrics['rougeL']:.4f}")
    print(f"\nSaved to: {args.output}")


if __name__ == "__main__":
    main()
